export const GET_HABIT_LIST = 'GET_HABIT_LIST';
export const GET_CURRENT_UPDATED_HABIT = 'GET_CURRENT_UPDATED_HABIT';
export const HABIT_MAX_INDEX = 'HABIT_MAX_INDEX';
export const GET_HABIT_BY_ID = 'GET_HABIT_BY_ID';
